build:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash
  - chef-solo -v
  - gem install berkshelf
  - berks install -p cookbooks
  - chef-solo -c solo.rb
  - composer install --ansi --no-progress --no-dev --no-interaction
