build:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash
  - sudo apt-get update
  - sudo apt-get install -y ruby-dev
  - sudo gem install bundler --no-ri --no-rdoc
  - bundle install --deployment
  - bundle exec berks install
  - chef-solo -c solo.rb -p cookbooks
  - composer install --ansi --no-progress --no-dev --no-interaction
